Dask Distributed Write Fix
scverse/anndata pull request #1079
Opened 2023-07-26 17:16 UTC by syelman

Hi,
This issue appears when one tries to use dask distributed then write https://github.com/dask/distributed/issues/780.
I did what xarray does for this https://github.com/pydata/xarray/pull/1179/files.

Not sure why the lock is global though for now.

Ping @ivirshup @flying-sheep

2023-07-27 12:18 UTC, flying-sheep commented
is there a way to test this?

2023-07-28 14:59 UTC, syelman commented
@flying-sheep  added tests, and it now fails for h5py :D. I thought I could just go with whatever xarray did at https://github.com/pydata/xarray/pull/1179/files. But now I realize this was from 2017 so I will need investigate a bit more closely.

2023-08-22 12:19 UTC, syelman commented
Hey @flying-sheep @ilan-gold, it should be ready for review once this test passes. I ended up not adding h5ad support for distributed writing and just giving an error. To fix we would need to create a file manager class or so: https://github.com/pydata/xarray/issues/4242

2023-08-22 12:23 UTC, flying-sheep commented on anndata/tests/test_dask.py
> +@pytest.mark.dependency(depends=[""])
this needs to go!

2023-08-22 12:25 UTC, flying-sheep requested changes

2023-08-22 12:25 UTC, flying-sheep commented on pyproject.toml
> +    "dask[distributed]",
```suggestion
    "dask[array,distributed]",
```

2023-08-22 12:25 UTC, flying-sheep commented on anndata/tests/test_dask.py
> +    dd = pytest.importorskip("dask.distributed")
```suggestion
@needs('dask.distributed')
def test_dask_distributed_write(adata, tmp_path, diskfmt):
    import dask.array as da
    import dask.distributed as dd
    import numpy as np
```

2023-08-25 09:26 UTC, syelman commented
Hey @flying-sheep could you perhaps merge this? I created an issue for h5py version here: https://github.com/scverse/anndata/issues/1105. But until I create a PR for that separately, I would like to create a notebook for concat_on_disk, which uses distributed writing for tests.

2023-08-25 12:04 UTC, flying-sheep approved these changes

2023-08-25 12:50 UTC, ivirshup commented
Alright I think we can merge. But I want to follow up.

Looking through xarray, it doesn't seem like they use this kind of solution for zarr, but do for hdf5. However here, we are using this solution for zarr and it does not work for hdf5. This is a bit disconcerting and a little concerning.

I vaguely understand why this isn't working for us with hdf5, xarray has some handling for this as mentioned above.

I do not understand what the are doing as to not need this for zarr.

I will go ask xarray/ zarr people to take a look and see if they can suggest a better solution.

2023-08-25 12:51 UTC, merged