(fix): subsetting with empty list
scverse/anndata pull request #1243
Opened 2023-11-28 09:40 UTC by ilan-gold

- [x] Closes #1149
- [x] Tests added
- [x] Release note added (or unnecessary)

2023-11-30 11:56 UTC, ilan-gold commented
@flying-sheep So you're saying we should catch the error and then report back that the data types are mixed?  Just a side note, this behavior of mixed types doesn't seem to work so this would not be a regression:

```python
from anndata.tests.helpers import gen_adata
adata = gen_adata((100, 100))
adata[[0, 2], :] # good
adata[['cell5'], :] # good
adata[[0, 2, 'cell5'], :] # bad
```

2023-11-30 12:43 UTC, ilan-gold commented
Sounds good @flying-sheep

2023-11-30 16:16 UTC, flying-sheep requested changes

2023-11-30 16:16 UTC, flying-sheep commented on anndata/_core/index.py
> +            indexer = np.array(indexer, dtype=dtype)
```suggestion
        try:
            indexer = np.array(indexer, dtype=dtype)
        except ValueError as e:
            msg = "Mixed type list indexers not supported."
            raise ValueError(msg) from e
```

2023-11-30 16:18 UTC, flying-sheep approved these changes

2023-11-30 16:20 UTC, flying-sheep commented
why no release note?

2023-12-01 08:03 UTC, ilan-gold commented
I guess I didn't know what qualified as "unnecessary" for a release note and this seemed like one of those things.

2023-12-01 09:34 UTC, flying-sheep commented
Hmm, guess if that's not in the contribution guide we should add it, and if it is, we should link it.

As far as I understand, release notes are not encouraged if an unreleased feature gets modified or if the change is purely development process focused (tests, doc building, ...). This is a bugfix to a live feature, so it should get a release note.

2023-12-01 10:36 UTC, flying-sheep requested changes

2023-12-03 12:41 UTC, merged