(fix): raise error on non-integer floating types
scverse/anndata pull request #1746
Opened 2024-11-08 10:09 UTC by ilan-gold

- [x] Closes #1735
- [x] Tests added
- [ ] Release note added (or unnecessary)

2024-11-08 17:18 UTC, flying-sheep requested changes

2024-11-08 17:18 UTC, flying-sheep commented on src/anndata/_core/index.py
> +        if isinstance(indexer, np.ndarray) and indexer.dtype == float:
Please fix the comparison so it doesn’t only work with float64:

```pycon
>>> np.dtype(np.float64) == float
True
>>> np.dtype(np.float32) == float
False
```

(and parametrize the tests please)

2024-11-11 09:31 UTC, flying-sheep approved these changes

2024-11-11 10:26 UTC, ilan-gold commented on tests/test_views.py
> +        gen_adata((10, 10))[index]
@flying-sheep is the goal here to ensure dtype is checked on sparse matrices as well? I think it's enough to check the numpy arrays.  Also we can't case a list.  Also `dtype` is not accessible outside of its parametrization/the test.

2024-12-10 10:04 UTC, flying-sheep commented on tests/test_views.py
> +        gen_adata((10, 10))[index]
> is the goal here to ensure dtype is checked on sparse matrices as well?

yup, but it’s not that important, I agree with

> I think it's enough to check the numpy arrays.

2024-12-10 10:04 UTC, merged